// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PropiedadesMinimalAPI.Data;

#nullable disable

namespace PropiedadesMinimalAPI.Migrations
{
    [DbContext(typeof(PropertiesDBContext))]
    partial class PropertiesDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PropiedadesMinimalAPI.Models.Property", b =>
                {
                    b.Property<int>("IdPropiedad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPropiedad"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaCreacion")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("NombrePropiedad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPropiedad");

                    b.ToTable("Property");

                    b.HasData(
                        new
                        {
                            IdPropiedad = 1,
                            Activa = true,
                            Descripcion = "Hermosa casa con jardín y alberca",
                            FechaCreacion = new DateTime(2026, 8, 4, 21, 19, 34, 158, DateTimeKind.Local).AddTicks(9337),
                            NombrePropiedad = "Casa las palmas",
                            Ubicacion = "Tuxtla Gutierrez"
                        },
                        new
                        {
                            IdPropiedad = 2,
                            Activa = true,
                            Descripcion = "Cómodo departamento cerca del parque central",
                            FechaCreacion = new DateTime(2026, 8, 6, 21, 19, 34, 158, DateTimeKind.Local).AddTicks(9356),
                            NombrePropiedad = "Departamento centro",
                            Ubicacion = "Tuxtla Gutierrez"
                        },
                        new
                        {
                            IdPropiedad = 3,
                            Activa = false,
                            Descripcion = "Amplia casa en zona residencial privada",
                            FechaCreacion = new DateTime(2026, 7, 30, 21, 19, 34, 158, DateTimeKind.Local).AddTicks(9358),
                            NombrePropiedad = "Casa residencial",
                            Ubicacion = "Tuxtla Gutierrez"
                        },
                        new
                        {
                            IdPropiedad = 4,
                            Activa = true,
                            Descripcion = "Terreno de 500m2 con vista al bosque",
                            FechaCreacion = new DateTime(2026, 8, 9, 21, 19, 34, 158, DateTimeKind.Local).AddTicks(9360),
                            NombrePropiedad = "Terreno el vergel",
                            Ubicacion = "Chiapa de Corzo"
                        },
                        new
                        {
                            IdPropiedad = 5,
                            Activa = true,
                            Descripcion = "Casa de dos pisos con terraza",
                            FechaCreacion = new DateTime(2026, 7, 25, 21, 19, 34, 158, DateTimeKind.Local).AddTicks(9362),
                            NombrePropiedad = "Casa san miguel",
                            Ubicacion = "San Cristobal"
                        },
                        new
                        {
                            IdPropiedad = 6,
                            Activa = false,
                            Descripcion = "Departamento nuevo, totalmente equipado",
                            FechaCreacion = new DateTime(2026, 8, 11, 21, 19, 34, 158, DateTimeKind.Local).AddTicks(9363),
                            NombrePropiedad = "Departamento moderno",
                            Ubicacion = "Tuxtla Gutierrez"
                        },
                        new
                        {
                            IdPropiedad = 7,
                            Activa = true,
                            Descripcion = "Propiedad rural con jardín y huerta",
                            FechaCreacion = new DateTime(2026, 8, 2, 21, 19, 34, 158, DateTimeKind.Local).AddTicks(9365),
                            NombrePropiedad = "Casa campo",
                            Ubicacion = "Chiapa de Corzo"
                        },
                        new
                        {
                            IdPropiedad = 8,
                            Activa = true,
                            Descripcion = "Local en zona de alto tránsito peatonal",
                            FechaCreacion = new DateTime(2026, 8, 7, 21, 19, 34, 158, DateTimeKind.Local).AddTicks(9366),
                            NombrePropiedad = "Local comercial",
                            Ubicacion = "Tuxtla Gutierrez"
                        },
                        new
                        {
                            IdPropiedad = 9,
                            Activa = false,
                            Descripcion = "Casa estilo colonial con 3 recámaras",
                            FechaCreacion = new DateTime(2026, 7, 20, 21, 19, 34, 158, DateTimeKind.Local).AddTicks(9368),
                            NombrePropiedad = "Casa colonial",
                            Ubicacion = "San Cristobal"
                        },
                        new
                        {
                            IdPropiedad = 10,
                            Activa = true,
                            Descripcion = "Terreno con acceso principal para negocio",
                            FechaCreacion = new DateTime(2026, 8, 13, 21, 19, 34, 158, DateTimeKind.Local).AddTicks(9369),
                            NombrePropiedad = "Terreno comercial",
                            Ubicacion = "Tuxtla Gutierrez"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
